const resp1 = {
  data: [
    {
      id: 29,
      role: null,
      collection: "subscriber",
      action: "create",
      permissions: {},
      validation: {},
      presets: null,
      fields: ["*"],
    },
    {
      id: 41,
      role: null,
      collection: "directus_files",
      action: "read",
      permissions: { _and: [{ folder: { name: { _eq: "Public Files" } } }] },
      validation: {},
      presets: null,
      fields: ["*"],
    },
    {
      id: 44,
      role: null,
      collection: "post",
      action: "read",
      permissions: { _and: [{ status: { _eq: "published" } }] },
      validation: null,
      presets: null,
      fields: [
        "slug",
        "user_created",
        "date_created",
        "status",
        "sort",
        "user_updated",
        "title",
        "tags",
        "author",
        "content",
        "date",
        "featured_image",
        "date_updated",
        "description",
      ],
    },
    {
      id: 46,
      role: null,
      collection: "directus_users",
      action: "read",
      permissions: {
        _and: [
          { _or: [{ id: { _eq: "$CURRENT_USER" } }, { posts: { status: { _eq: "published" } } }] },
        ],
      },
      validation: null,
      presets: null,
      fields: [
        "first_name",
        "last_name",
        "email",
        "avatar",
        "title",
        "description",
        "tags",
        "posts",
        "role",
        "id",
        "location",
        "password",
        "language",
      ],
    },
    {
      id: 48,
      role: null,
      collection: "form_entry",
      action: "create",
      permissions: {},
      validation: {},
      presets: null,
      fields: ["*"],
    },
  ],
}

const resp2 = {
  data: [
    {
      id: 29,
      role: null,
      collection: "subscriber",
      action: "create",
      permissions: {},
      validation: {},
      presets: null,
      fields: ["*"],
    },
    {
      id: 41,
      role: null,
      collection: "directus_files",
      action: "read",
      permissions: { _and: [{ folder: { name: { _eq: "Public Files" } } }] },
      validation: {},
      presets: null,
      fields: ["*"],
    },
    {
      id: 44,
      role: null,
      collection: "post",
      action: "read",
      permissions: { _and: [{ status: { _eq: "published" } }] },
      validation: null,
      presets: null,
      fields: [
        "slug",
        "user_created",
        "date_created",
        "status",
        "sort",
        "user_updated",
        "title",
        "tags",
        "author",
        "content",
        "date",
        "featured_image",
        "date_updated",
        "description",
      ],
    },
    {
      id: 46,
      role: null,
      collection: "directus_users",
      action: "read",
      permissions: {
        _and: [
          { _or: [{ id: { _eq: "$CURRENT_USER" } }, { posts: { status: { _eq: "published" } } }] },
        ],
      },
      validation: null,
      presets: null,
      fields: [
        "first_name",
        "last_name",
        "email",
        "avatar",
        "title",
        "description",
        "tags",
        "posts",
        "role",
        "id",
        "location",
        "password",
        "language",
      ],
    },
    {
      id: 48,
      role: null,
      collection: "form_entry",
      action: "create",
      permissions: {},
      validation: {},
      presets: null,
      fields: ["*"],
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_collections",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_fields",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { role: { _eq: "$CURRENT_ROLE" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_permissions",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_relations",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { user: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_activity",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: { comment: { _nnull: true } },
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_activity",
      action: "create",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {
        _or: [
          { user: { _eq: "$CURRENT_USER" } },
          { _and: [{ user: { _null: true } }, { role: { _eq: "$CURRENT_ROLE" } }] },
          { _and: [{ user: { _null: true } }, { role: { _null: true } }] },
        ],
      },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_presets",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: { user: { _eq: "$CURRENT_USER" } },
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_presets",
      action: "create",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { user: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_presets",
      action: "update",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { user: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_presets",
      action: "delete",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { id: { _eq: "$CURRENT_ROLE" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_roles",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: {},
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_settings",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { recipient: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_notifications",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { recipient: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["status"],
      system: true,
      collection: "directus_notifications",
      action: "update",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { user_created: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: ["*"],
      system: true,
      collection: "directus_shares",
      action: "read",
    },
    {
      role: "b2667034-afbb-4bd2-aa62-54f72b446c04",
      permissions: { id: { _eq: "$CURRENT_USER" } },
      validation: null,
      presets: null,
      fields: [
        "id",
        "first_name",
        "last_name",
        "last_page",
        "email",
        "password",
        "location",
        "title",
        "description",
        "tags",
        "preferences_divider",
        "avatar",
        "language",
        "theme",
        "tfa_secret",
        "status",
        "role",
      ],
      system: true,
      collection: "directus_users",
      action: "read",
    },
  ],
}
